### ISSUE TITLE
Postgres Repository should return room.Room's in case filters is None

### ISSUE THREAD

**Issue by godiedelrio** [pycabook/rentomatic#1]
The query.all() results should be converted to the core entity room.Room in

https://github.com/pycabook/rentomatic/blob/3c80a2e48fa8926eedceca59fd1cad2997d0f327/rentomatic/repository/postgresrepo.py#L27

before returning them. ¿Is this conversion code part of what is called "Interface adapters" in the Clean Architecture?

Nice work!

**Comment by godiedelrio** [comment]
In Mongo Repository this is handled correctly.

**Comment by lgiordani** [comment]
You are so right. It's actually handled correctly some lines later. Thanks, I'll fix it as soon as possible. It involves changing both the book and the repository, so it will take me a couple of days.

**Comment by lgiordani** [comment]
Fixed in version 1.0.7 of the book, thank you! The repository has been force pushed to stay in sync with the book
