### ISSUE TITLE
Missing click requirement

### ISSUE THREAD

**Issue by staticdev** [pycabook/rentomatic#11]
* Rentomatic version: latest
* Python version: DC
* Operating System: DC

### Description

manage.py uses click, but it is not part of dev, test or prod requirements (in the book and repo).

### What I Did

I would add that to requirements/test.txt or maybe dev.txt (I usually have only prod and dev requirements for my projects to keep it simple).

**Comment by lgiordani** [comment]
`click` is a dependency of Flask, and will be installed by it (see https://github.com/pallets/flask/blob/main/requirements/dev.txt#L27). I think you might have forgotten to run `pip install -r requirements/dev.txt` after you added `Flask` in `requirements/prod.txt` (Chapter 6 - "Create SQLAlchemy classes"). Can you please confirm? Thanks!

**Comment by staticdev** [comment]
@lgiordani I just mentioned this actually since you are explicitly using `click` on `manage.py`. I got no error actually. It was more a suggestion to have everything you are importing on requirements. If you feel this is not an issue feel free to close.

**Comment by lgiordani** [comment]
Thanks @staticdev. I think however that `click` should be installed automatically and be available on the command line after you installed Flask, so everything should be OK anyway. Thanks!
