### ISSUE TITLE
Error with price filters

### ISSUE THREAD

**Issue by lrfuentesw** [pycabook/rentomatic#2]
* Rentomatic version: [chapter-3-the-repository](https://github.com/pycabook/rentomatic/releases/tag/chapter-3-the-repository)
* Python version: 3.6.8
* Operating System: Ubuntu Budgie 18-04

### Description

I want to get a list of rooms with filter price__eq

### What I Did
 ```$ curl 'http://localhost:5000/rooms?filter_price__gt=2&filter_price__lt=6'```
I get
``` {"type": "SystemError", "message": "TypeError: '>' not supported between instances of 'int' and 'str'"}```
But the ```test_get_with_filters``` pass which i find odd because it tests a get call with the same filters

It is solved casting ```filters['price__eq']```, ```filters['price__eq']``` and ```filters['price__eq']```  to int in memrepo.py

**Comment by lgiordani** [comment]
Thanks! I'm going to have a look asap and post updates here

**Comment by lgiordani** [comment]
Hi! I'm working on this, the error is simple (there is no check that filters work when they are expressed as strings and not integers), but it takes some time to reconcile the code and the text of the book. Thanks, I'll publish the fix in the next few days

**Comment by lgiordani** [comment]
Fixed in the latest master (force pushed to retro-fix the issue). Book version 1.0.11 contains the correct code. Thank you very much!
