### ISSUE TITLE
Text adjustment suggestion, RoomEncoder to RoomJsonEncoder

### ISSUE THREAD

**Issue by rodrigodelmonte** [pycabook/rentomatic#3]
* Rentomatic version:  Git tag chapter-2-serializers
* Python version: 3.7
* Operating System: Mac

### Description

The code works perfectly, just a suggestion to adjust the explanation on page `88`.

**Sentence:**

> Providing a class that inherits from json.JSONEncoder let us use the json.dumps(room, cls=RoomEncoder) syntax to serialize the model.

**Should be:**

> Providing a class that inherits from json.JSONEncoder let us use the json.dumps(room, cls=RoomJsonEncoder) syntax to serialize the model.

To keep consistency with the code example.

**Comment by lgiordani** [comment]
@rodrigodelmonte apologies for never coming back to you on this. That a good suggestion, thanks for spotting it. I'm preparing the second edition of the book these days and I will add this there. Thanks again!

**Comment by lgiordani** [comment]
Hi! This has been implemented in the second edition of the book and in the new version of the code. Thanks for your help!
